
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://unigdc.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "UniGDC"
title: "UHS Game Dev. Club"
description: "University High School Game Development Club, since 2016."
keywords: ""
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/logo_2016-2017.png"

background-img: "http://www.universityhigh.org/files/athletics/slideshow/athletics2.JPG"

logo-of-the-year: "/img/logo_2016-2017.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Awesome games, made with ♥ and your hands."
  - text: "Welcome to the UHS Game Development Club!"
  - text: "University High School Game Development Club"
  - text: "Regular meetings every Wednesdays at the Library!"

me-img: "/img/school-logo.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#3985FC"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: False

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: False
reddit-share: False
google-plus-share: True
tumblr-share: True
pinterest-share: False
pocket-share: False
vkontakte-share: False

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/school-logo.jpg"
    date: "2016-2017"
    description: "The first year of the club!"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "unigdc@gmail.com"
discord: "fCxNS4M"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
#author_blurb: "John Smith is an awesome person. He lives in Flatland, where he works on two-dimensional engineering projects. In his spare time, John likes to eat cotton candy."
#author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "envelope"
    url: "mailto:unigdc@gmail.com"
  - title: "github"
    url: "https://github.com/UniGDC"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

#############
# Resources #
#############

resources:
  - title: "Club Constitution"
    url: "/constitution.html"
  - title: "List of Members"
    url: "/memberslist.html"
  - title: "Club Meeting Records Archive"
    url: "/categories/hours.html"

latest-constitution-url: "/docs/2017/02/01/constitution.html"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Resources: 'resources'
  Discord: 'discord'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji

markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1