# Site settings
title: UniGDC Official Website
email: unigdc@gmail.com
description: Welcome to University High School Game Development Club Official Website!
baseurl: ""
url: "http://unigdc.github.io"
twitter_username: UniGDC
github_username:  UniGDC

# Build settings
markdown: kramdown
